Exception handling
ystankevych/book-app pull request #4
Opened 2023-10-17 22:26 UTC by ystankevych

2023-10-20 10:14 UTC, liliia-ponomarenko requested changes
good job! Let’s  improve your solution ;)

2023-10-20 10:14 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/exception/CustomGlobalExceptionHandler.java
> +
```suggestion
```

2023-10-20 10:14 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/exception/errors/BookApiError.java
> +public record BookApiError(
```suggestion
public record BookApiException(
```

2023-10-20 10:14 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/exception/errors/BookApiError.java
> +package mate.academy.exception.errors;
move it to exception package and remove errors

2023-10-20 10:14 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/service/BookServiceImpl.java
> +        }
for now, I prefer not to complicate your logic with additional checking

2023-10-23 07:21 UTC, Elena-Bruyako approved these changes
Good job!

2023-10-23 07:21 UTC, Elena-Bruyako commented on src/main/java/mate/academy/exception/CustomGlobalExceptionHandler.java
> +    protected ResponseEntity<Object> handleEntityNotFoundException(
```suggestion
    protected ResponseEntity<Object> handleEntityNotFoundException(EntityNotFoundException ex) {
```

2023-10-23 07:21 UTC, Elena-Bruyako commented on src/main/java/mate/academy/controller/BookController.java
> +    @ResponseStatus(HttpStatus.NO_CONTENT)
If you added response status for one endpoint, let's add for others

2023-10-23 08:56 UTC, merged